GET http://localhost:8001/pets
###
GET http://localhost:8001/logs?pet_id=98
###
POST http://localhost:8001/logs
Content-Type:  application/json

{
 "pet_id": 98,
 "description": "Hair spray",
 "status": "in progress"
}
###
POST http://localhost:8001/pets
Content-Type:  application/json

{
   "name": "Mouse",
   "dob": "2017-01-01",
   "client_email": "test@example.com",
   "archived": false
   }
###
PATCH  http://localhost:8001/pets/106
Content-Type:  application/json

{
  "name": "James Bond" 
}
###

POST  http://localhost:8001/prescriptions
Content-Type:  application/json

{
    "pet_id": 152,
    "comment": "for the best",
    "medication_id": 1
  }
